# Workflow for building and deploying a Jekyll site to GitHub Pages

name: Deploy Jekyll site to Pages

on:
  # Trigger workflow on pushes to the default branch
  push:
    branches: ["main"]

  # Allow manual triggering from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment runs at a time for the 'pages' group.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job to build the Jekyll site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'   # Ruby version; if .ruby-version exists, this is optional
          bundler-cache: true   # Automatically installs and caches gems

      - name: Disable Gemfile.lock frozen mode
        run: bundle config set frozen false

      - name: Install dependencies
        run: bundle install

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build site with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3

  # Job to deploy the built site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
